library(ggplot2)
library(gridExtra)
library(data.table)
library(XML)
library(xml2)
library(tidyverse)
library(cluster)
library(Rcpp)
library(RcppArmadillo)
library(RColorBrewer)

source("import_data.R")
source("geometry_functions.R")
source("douglas_peucker.R")
source("marginal_histogram.R")
source("add_attributes.R")
source("visualize.R")
source("rename_proteins.R")
sourceCpp("DPRCPP.cpp")


